branches:
  only:
    - develop

language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

script: ./gradlew build :library:test
