language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.4
    - android-23
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew clean test --info

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
