language: android

android:
  components:
    - build-tools-23.1.0
    - android-23
    - extra-android-m2repository

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2

script: ./gradlew :library:build :library:test
